branches:
  only:
  - master
  - dev
dist: bionic
language: php
php:
  - 7.3
node_js:
  - 10.20.1
services:
  - mysql
cache:
  directories:
    - node_modules
    - vendor
before_script:
  - cp .env.travis .env
  - cp phpunit.xml.travis phpunit.xml
  - sudo mysql -e 'create database homestead;'
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate
  - npm install
script:
  - php artisan test
  - npm test